homepage:
    path:     /
    defaults: { _controller: TheBlackLionLExSplitterBundle:Default:index }

addpayment:
    path:     /addpayment
    defaults: { _controller: TheBlackLionLExSplitterBundle:Payment:add }
